// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProfAly.CMS.Infrastructure.Persistence;

#nullable disable

namespace ProfAly.CMS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ActivityGroupId", "SortOrder");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.ActivityGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("ActivityGroup");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.ActivityGroupTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityGroupId", "Culture")
                        .IsUnique();

                    b.ToTable("ActivityGroupTranslation", t =>
                        {
                            t.HasCheckConstraint("CK_ActivityGroupTranslation_Culture", "Culture IN ('ar','en','fr')");
                        });
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.ActivityTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId", "Culture")
                        .IsUnique();

                    b.ToTable("ActivityTranslation", t =>
                        {
                            t.HasCheckConstraint("CK_ActivityTranslation_Culture", "Culture IN ('ar','en','fr')");
                        });
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.CategoryTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "Culture")
                        .IsUnique();

                    b.HasIndex("Culture", "Slug")
                        .IsUnique();

                    b.ToTable("CategoryTranslation", t =>
                        {
                            t.HasCheckConstraint("CK_CategoryTranslation_Culture", "Culture IN ('ar','en','fr')");
                        });
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsRead", "CreatedUtc");

                    b.ToTable("ContactMessage");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Content.ContentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CoverImageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("EventDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PdfFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CoverImageId");

                    b.HasIndex("PdfFileId");

                    b.HasIndex("ContentType", "IsFeatured", "IsPublished");

                    b.HasIndex("ContentType", "IsPublished", "SortOrder");

                    b.ToTable("ContentItem");

                    b.HasDiscriminator<string>("ContentType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Content.ContentItemTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Authors")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorshipRole")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Journal")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(70)
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResearcherName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentItemId", "Culture")
                        .IsUnique();

                    b.HasIndex("Culture", "Slug")
                        .IsUnique();

                    b.ToTable("ContentItemTranslation", t =>
                        {
                            t.HasCheckConstraint("CK_ContentItemTranslation_Culture", "Culture IN ('ar','en','fr')");
                        });
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.ContentEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContentItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentItemId", "EventType", "CreatedUtc");

                    b.ToTable("ContentEvent", t =>
                        {
                            t.HasCheckConstraint("CK_ContentEvent_Culture", "Culture IN ('ar','en','fr')");
                        });
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.ContentItemCategory", b =>
                {
                    b.Property<int>("ContentItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContentItemId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ContentItemCategory");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Period")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Level", "SortOrder");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.CourseTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Institution")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Culture")
                        .IsUnique();

                    b.ToTable("CourseTranslation", t =>
                        {
                            t.HasCheckConstraint("CK_CourseTranslation_Culture", "Culture IN ('ar','en','fr')");
                        });
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Credibility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LogoMediaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("LogoMediaId");

                    b.HasIndex("SortOrder");

                    b.ToTable("Credibility");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.CredibilityTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CredibilityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CredibilityId", "Culture")
                        .IsUnique();

                    b.ToTable("CredibilityTranslation", t =>
                        {
                            t.HasCheckConstraint("CK_CredibilityTranslation_Culture", "Culture IN ('ar','en','fr')");
                        });
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.ExperienceEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("StartDateUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("ExperienceEntry");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.ExperienceEntryTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExperienceEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodLabel")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceEntryId", "Culture")
                        .IsUnique();

                    b.ToTable("ExperienceEntryTranslation", t =>
                        {
                            t.HasCheckConstraint("CK_ExperienceEntryTranslation_Culture", "Culture IN ('ar','en','fr')");
                        });
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.MediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AltText")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaKind")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StoredFileName")
                        .IsUnique();

                    b.HasIndex("MediaKind", "CreatedUtc");

                    b.ToTable("MediaFile");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Kind", "SortOrder");

                    b.ToTable("Membership");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.MembershipTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int>("MembershipId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId", "Culture")
                        .IsUnique();

                    b.ToTable("MembershipTranslation", t =>
                        {
                            t.HasCheckConstraint("CK_MembershipTranslation_Culture", "Culture IN ('ar','en','fr')");
                        });
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.PageSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PageKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("PageKey")
                        .IsUnique();

                    b.ToTable("PageSection");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.PageSectionTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Heading")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PageSectionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PageSectionId", "Culture")
                        .IsUnique();

                    b.ToTable("PageSectionTranslation", t =>
                        {
                            t.HasCheckConstraint("CK_PageSectionTranslation_Culture", "Culture IN ('ar','en','fr')");
                        });
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.PageSeo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(70)
                        .HasColumnType("TEXT");

                    b.Property<string>("PageKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PageKey", "Culture")
                        .IsUnique();

                    b.ToTable("PageSeo", t =>
                        {
                            t.HasCheckConstraint("CK_PageSeo_Culture", "Culture IN ('ar','en','fr')");
                        });
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.PageView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc");

                    b.ToTable("PageView", t =>
                        {
                            t.HasCheckConstraint("CK_PageView_Culture", "Culture IN ('ar','en','fr')");
                        });
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhotoMediaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhotoMediaId");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.ProfileTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CvFileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullBio")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Languages")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaritalStatus")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Positioning")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortBio")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CvFileId");

                    b.HasIndex("ProfileId", "Culture")
                        .IsUnique();

                    b.ToTable("ProfileTranslation", t =>
                        {
                            t.HasCheckConstraint("CK_ProfileTranslation_Culture", "Culture IN ('ar','en','fr')");
                        });
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Qualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("Qualification");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.QualificationTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("QualificationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QualificationId", "Culture")
                        .IsUnique();

                    b.ToTable("QualificationTranslation", t =>
                        {
                            t.HasCheckConstraint("CK_QualificationTranslation_Culture", "Culture IN ('ar','en','fr')");
                        });
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Redirect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromPath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToPath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FromPath")
                        .IsUnique();

                    b.ToTable("Redirect", t =>
                        {
                            t.HasCheckConstraint("CK_Redirect_StatusCode", "StatusCode IN (301, 302)");
                        });
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.SiteSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultCulture")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultTheme")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("FacebookUrl")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LogoMediaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryColor")
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatsAppNumber")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LogoMediaId");

                    b.ToTable("SiteSettings", t =>
                        {
                            t.HasCheckConstraint("CK_SiteSettings_DefaultCulture", "DefaultCulture IN ('ar','en','fr')");
                        });
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.SiteSettingsTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("FooterText")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SiteSettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SiteTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tagline")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SiteSettingsId", "Culture")
                        .IsUnique();

                    b.ToTable("SiteSettingsTranslation", t =>
                        {
                            t.HasCheckConstraint("CK_SiteSettingsTranslation_Culture", "Culture IN ('ar','en','fr')");
                        });
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.SkillTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SkillId", "Culture")
                        .IsUnique();

                    b.ToTable("SkillTranslation", t =>
                        {
                            t.HasCheckConstraint("CK_SkillTranslation_Culture", "Culture IN ('ar','en','fr')");
                        });
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.StatItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Suffix")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("StatItem");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.StatItemTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("StatItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StatItemId", "Culture")
                        .IsUnique();

                    b.ToTable("StatItemTranslation", t =>
                        {
                            t.HasCheckConstraint("CK_StatItemTranslation_Culture", "Culture IN ('ar','en','fr')");
                        });
                });

            modelBuilder.Entity("ProfAly.CMS.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Content.Book", b =>
                {
                    b.HasBaseType("ProfAly.CMS.Domain.Entities.Content.ContentItem");

                    b.HasDiscriminator().HasValue("Book");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Content.EnrichmentItem", b =>
                {
                    b.HasBaseType("ProfAly.CMS.Domain.Entities.Content.ContentItem");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("EnrichmentItem");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Content.Project", b =>
                {
                    b.HasBaseType("ProfAly.CMS.Domain.Entities.Content.ContentItem");

                    b.Property<string>("ProjectStatus")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Project");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Content.Publication", b =>
                {
                    b.HasBaseType("ProfAly.CMS.Domain.Entities.Content.ContentItem");

                    b.Property<string>("Doi")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Publication");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Content.ResearchPaper", b =>
                {
                    b.HasBaseType("ProfAly.CMS.Domain.Entities.Content.ContentItem");

                    b.Property<string>("Doi")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.ToTable("ContentItem", t =>
                        {
                            t.Property("Doi")
                                .HasColumnName("ResearchPaper_Doi");
                        });

                    b.HasDiscriminator().HasValue("ResearchPaper");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Content.Resource", b =>
                {
                    b.HasBaseType("ProfAly.CMS.Domain.Entities.Content.ContentItem");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.ToTable("ContentItem", t =>
                        {
                            t.Property("ResourceType")
                                .HasColumnName("ResourceType1");
                        });

                    b.HasDiscriminator().HasValue("Resource");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Content.Thesis", b =>
                {
                    b.HasBaseType("ProfAly.CMS.Domain.Entities.Content.ContentItem");

                    b.Property<string>("DegreeLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.HasIndex("RelationshipType", "DegreeLevel");

                    b.HasDiscriminator().HasValue("Thesis");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Content.Video", b =>
                {
                    b.HasBaseType("ProfAly.CMS.Domain.Entities.Content.ContentItem");

                    b.Property<string>("YouTubeVideoId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Video");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ProfAly.CMS.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ProfAly.CMS.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProfAly.CMS.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ProfAly.CMS.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Activity", b =>
                {
                    b.HasOne("ProfAly.CMS.Domain.Entities.ActivityGroup", "ActivityGroup")
                        .WithMany("Activities")
                        .HasForeignKey("ActivityGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityGroup");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.ActivityGroupTranslation", b =>
                {
                    b.HasOne("ProfAly.CMS.Domain.Entities.ActivityGroup", "ActivityGroup")
                        .WithMany("Translations")
                        .HasForeignKey("ActivityGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityGroup");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.ActivityTranslation", b =>
                {
                    b.HasOne("ProfAly.CMS.Domain.Entities.Activity", "Activity")
                        .WithMany("Translations")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.CategoryTranslation", b =>
                {
                    b.HasOne("ProfAly.CMS.Domain.Entities.Category", "Category")
                        .WithMany("Translations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Content.ContentItem", b =>
                {
                    b.HasOne("ProfAly.CMS.Domain.Entities.MediaFile", "CoverImage")
                        .WithMany()
                        .HasForeignKey("CoverImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProfAly.CMS.Domain.Entities.MediaFile", "PdfFile")
                        .WithMany()
                        .HasForeignKey("PdfFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CoverImage");

                    b.Navigation("PdfFile");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Content.ContentItemTranslation", b =>
                {
                    b.HasOne("ProfAly.CMS.Domain.Entities.Content.ContentItem", "ContentItem")
                        .WithMany("Translations")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentItem");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.ContentEvent", b =>
                {
                    b.HasOne("ProfAly.CMS.Domain.Entities.Content.ContentItem", "ContentItem")
                        .WithMany("Events")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentItem");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.ContentItemCategory", b =>
                {
                    b.HasOne("ProfAly.CMS.Domain.Entities.Category", "Category")
                        .WithMany("ContentLinks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProfAly.CMS.Domain.Entities.Content.ContentItem", "ContentItem")
                        .WithMany("Categories")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ContentItem");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.CourseTranslation", b =>
                {
                    b.HasOne("ProfAly.CMS.Domain.Entities.Course", "Course")
                        .WithMany("Translations")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Credibility", b =>
                {
                    b.HasOne("ProfAly.CMS.Domain.Entities.MediaFile", "Logo")
                        .WithMany()
                        .HasForeignKey("LogoMediaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Logo");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.CredibilityTranslation", b =>
                {
                    b.HasOne("ProfAly.CMS.Domain.Entities.Credibility", "Credibility")
                        .WithMany("Translations")
                        .HasForeignKey("CredibilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credibility");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.ExperienceEntryTranslation", b =>
                {
                    b.HasOne("ProfAly.CMS.Domain.Entities.ExperienceEntry", "ExperienceEntry")
                        .WithMany("Translations")
                        .HasForeignKey("ExperienceEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExperienceEntry");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.MembershipTranslation", b =>
                {
                    b.HasOne("ProfAly.CMS.Domain.Entities.Membership", "Membership")
                        .WithMany("Translations")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.PageSectionTranslation", b =>
                {
                    b.HasOne("ProfAly.CMS.Domain.Entities.PageSection", "PageSection")
                        .WithMany("Translations")
                        .HasForeignKey("PageSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PageSection");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Profile", b =>
                {
                    b.HasOne("ProfAly.CMS.Domain.Entities.MediaFile", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoMediaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.ProfileTranslation", b =>
                {
                    b.HasOne("ProfAly.CMS.Domain.Entities.MediaFile", "CvFile")
                        .WithMany()
                        .HasForeignKey("CvFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProfAly.CMS.Domain.Entities.Profile", "Profile")
                        .WithMany("Translations")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CvFile");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.QualificationTranslation", b =>
                {
                    b.HasOne("ProfAly.CMS.Domain.Entities.Qualification", "Qualification")
                        .WithMany("Translations")
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Qualification");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.SiteSettings", b =>
                {
                    b.HasOne("ProfAly.CMS.Domain.Entities.MediaFile", "Logo")
                        .WithMany()
                        .HasForeignKey("LogoMediaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Logo");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.SiteSettingsTranslation", b =>
                {
                    b.HasOne("ProfAly.CMS.Domain.Entities.SiteSettings", "SiteSettings")
                        .WithMany("Translations")
                        .HasForeignKey("SiteSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteSettings");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.SkillTranslation", b =>
                {
                    b.HasOne("ProfAly.CMS.Domain.Entities.Skill", "Skill")
                        .WithMany("Translations")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.StatItemTranslation", b =>
                {
                    b.HasOne("ProfAly.CMS.Domain.Entities.StatItem", "StatItem")
                        .WithMany("Translations")
                        .HasForeignKey("StatItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatItem");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Activity", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.ActivityGroup", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Category", b =>
                {
                    b.Navigation("ContentLinks");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Content.ContentItem", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Events");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Course", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Credibility", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.ExperienceEntry", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Membership", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.PageSection", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Profile", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Qualification", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.SiteSettings", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.Skill", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ProfAly.CMS.Domain.Entities.StatItem", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
